# Generated by Django 4.1.7 on 2023-03-17 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(max_length=30, verbose_name='Ticket-type name')),
                ('ticket_type_desc', models.TextField(verbose_name='Description')),
                ('ticket_type_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField(verbose_name='Ticket number')),
                ('raised_date', models.DateTimeField(auto_now_add=True, verbose_name='Raised Date')),
                ('issue_detail', models.TextField(verbose_name='Issue Details')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Response date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments by Teamlead')),
                ('ticket_status', models.IntegerField(choices=[('raised', 0), ('processing', 1), ('rejected', 2), ('closed', 3)], default=0)),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Closed date')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL)),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Response by')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type', to='main.ticket_type', verbose_name='Ticket type')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Team name')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[('manager', 0), ('employee', 1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.IntegerField(choices=[('pending', 0), ('approved', 1), ('rejected', 2)], default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='main.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='la_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
