# Generated by Django 4.1.7 on 2023-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team_userprofile_profilepicture_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.IntegerField(choices=[(0, 'Team Leader'), (1, 'Team Member')], default=2),
        ),
    ]
