# Generated by Django 4.1.7 on 2023-03-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userrole_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
