# Generated by Django 4.1.7 on 2023-04-20 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_remove_calenderevent_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(max_length=30, verbose_name='Ticket-type name')),
                ('ticket_type_desc', models.TextField(verbose_name='Description')),
                ('ticket_type_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ticket number')),
                ('raised_date', models.DateTimeField(auto_now_add=True, verbose_name='Raised Date')),
                ('issue_detail', models.TextField(verbose_name='Issue Details')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Issue date')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Response date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments by Teamlead')),
                ('ticket_status', models.IntegerField(choices=[(0, 'raised'), (1, 'processing'), (2, 'rejected'), (3, 'closed'), (4, 'Deleted')], default=0)),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Closed date')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_user', to=settings.AUTH_USER_MODEL)),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Response by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamfk', to='main.team')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type', to='main.ticket_type', verbose_name='Ticket type')),
            ],
        ),
    ]
