# Generated by Django 4.1.7 on 2023-04-20 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ticket_type_teamticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='applied_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
