# Generated by Django 4.1.7 on 2023-04-22 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_teamticket_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_ticket_user', to=settings.AUTH_USER_MODEL, verbose_name='Closed by'),
        ),
    ]
